#ifndef SENSORS_HANDLER_C_H
#define SENSORS_HANDLER_C_H

extern "C" {

enum SENSOR_IDS{
	SENSOR_LINE_AN,
	SENSOR_COLOR_RED,
	SENSOR_COLOR_GREEN,
	SENSOR_COLOR_BLUE,
	SENSOR_COMPASS_X,
	SENSOR_COMPASS_Y,
	SENSOR_COMPASS_Z,
	SENSOR_COMPASS_ANGLE,
	SENSOR_CRASH_BUTTON,
	SENSOR_FLAME_DIG,
	SENSOR_FLAME_AN,
	SENSOR_HCSR04,
	SENSOR_LINE_DIG,
	SENSOR_SHARP,
	MAX_SENSORS
};

int handle_sensor(int sensor_id, const int *data);

}

#endif /* end of include guard: SENSORS_HANDLER_C_H */
