#ifndef CONSOLE_CONSOLE_H
#define CONSOLE_CONSOLE_H

#include "stddef.h"
#include "console_autogenerated.h"
#include "iobase/iobase.h"

typedef struct cmd{
	char name[64];
	void (*Handle)(CIOBase &io, int argc, char **argv);
} cmd_t;

class CConsole{
public:
	CConsole();
	~CConsole(){};

	/* Sets cmd name and handler in m_Cmds array */
	bool RegisterCmd(CmdTypes type, void (*Handler)(CIOBase &io, int argc, char **argv));

	/* Calls cmd's handler that is located at ccmds folder */
	bool HandleCmd(CIOBase &io, char *cmdstr);

	/* Reads chars from CIOBase input untill we get cmd string */
	void WaitForCmd(CIOBase &io);
private:
	cmd_t m_Cmds[MAX_CMDS];
	size_t m_NumberOfCmds;
	size_t m_CmdsExist;
};

extern CConsole console;

#endif /* end of include guard: CONSOLE_CONSOLE_H */
